version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
        user: root
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - run:
          name: Unit tests
          working_directory: project
          command: |
            pwd
            ls
            bash ./scripts/test.sh
