version: "3.6"
services:

  fluentd:
    image: fluent/fluentd:v1.14.1-debian-1.0
    volumes:
      - ./log/fluent.conf:/fluentd/etc/fluent.conf
    command: ["-c", "/fluentd/etc/fluent.conf"]
